"use client";

import { useState } from "react";
import { CalendarDays, CloudRain, LoaderCircle, MapPin, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import type { ItineraryRecord } from "@/lib/server/plan";

export function ItineraryGenerator({
  tripId,
  initialItinerary,
  canGenerate,
}: {
  tripId: string;
  initialItinerary: ItineraryRecord | null;
  canGenerate: boolean;
}) {
  const [itinerary, setItinerary] = useState(initialItinerary);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function generate() {
    setLoading(true);
    setError(null);
    try {
      const response = await fetch(`/api/trips/${tripId}/itinerary`, { method: "POST" });
      const payload = await response.json().catch(() => null);
      if (!response.ok) throw new Error(payload?.error ?? "Couldn't generate the itinerary.");
      setItinerary(payload.itinerary as ItineraryRecord);
    } catch (generationError) {
      setError(generationError instanceof Error ? generationError.message : "Couldn't generate the itinerary.");
    } finally {
      setLoading(false);
    }
  }

  return (
    <section aria-label="Day-by-day itinerary" className="flex flex-col gap-4">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h2 className="font-display text-lg font-semibold leading-6 text-foreground">Your itinerary</h2>
          <p className="mt-1 text-[12.5px] leading-[18px] text-muted-foreground">
            {itinerary ? "Generated from your saved preferences." : "Complete all preferences, then generate your plan."}
          </p>
        </div>
        <Button onClick={() => void generate()} disabled={!canGenerate || loading} className="w-full sm:w-auto">
          {loading ? <LoaderCircle size={16} className="animate-spin" aria-hidden="true" /> : <Sparkles size={16} aria-hidden="true" />}
          {loading ? "Building itinerary…" : itinerary ? "Regenerate" : "Generate itinerary"}
        </Button>
      </div>

      {error ? <p role="alert" className="rounded-lg border border-destructive/30 bg-card p-3 text-sm text-destructive">{error}</p> : null}

      {itinerary ? (
        <div className="flex flex-col gap-4">
          <Card className="p-5">
            <p className="text-sm leading-6 text-foreground">{itinerary.content.summary}</p>
            <p className="mt-2 text-[11px] uppercase tracking-wide text-muted-foreground">
              Generated by {itinerary.content.generated_by === "claude" ? "Claude" : "local fallback"}
            </p>
          </Card>
          {itinerary.content.days.map((day) => (
            <Card key={day.date} as="article" className="overflow-hidden">
              <div className="flex items-center gap-2 border-b border-border bg-accent/40 px-5 py-4">
                <CalendarDays size={17} className="text-primary-deep" aria-hidden="true" />
                <div>
                  <h3 className="font-display text-base font-semibold text-foreground">{day.title}</h3>
                  <p className="text-[12px] text-muted-foreground">{day.date}</p>
                </div>
              </div>
              <ol className="divide-y divide-border">
                {day.items.map((item, index) => (
                  <li key={`${item.time_period}-${item.title}-${index}`} className="p-5">
                    <p className="text-[11px] font-semibold uppercase tracking-wide text-primary-deep">{item.time_period}</p>
                    <h4 className="mt-1 font-display text-[15px] font-semibold text-foreground">{item.title}</h4>
                    <p className="mt-1 flex items-start gap-1.5 text-[12.5px] text-muted-foreground">
                      <MapPin size={14} className="mt-0.5 shrink-0" aria-hidden="true" />{item.location}
                    </p>
                    <p className="mt-3 text-sm leading-5 text-foreground">{item.description}</p>
                    <p className="mt-2 text-[12.5px] leading-[18px] text-muted-foreground">Why: {item.rationale}</p>
                    {item.indoor_backup ? (
                      <p className="mt-2 flex items-start gap-1.5 text-[12px] leading-[18px] text-muted-foreground">
                        <CloudRain size={14} className="mt-0.5 shrink-0" aria-hidden="true" /> Backup: {item.indoor_backup}
                      </p>
                    ) : null}
                  </li>
                ))}
              </ol>
            </Card>
          ))}
          {itinerary.content.practical_tips.length > 0 ? (
            <Card className="p-5">
              <h3 className="font-display text-[15px] font-semibold text-foreground">Practical tips</h3>
              <ul className="mt-2 list-disc space-y-1 pl-5 text-[12.5px] leading-[18px] text-muted-foreground">
                {itinerary.content.practical_tips.map((tip) => <li key={tip}>{tip}</li>)}
              </ul>
            </Card>
          ) : null}
        </div>
      ) : null}
    </section>
  );
}
